dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 73f35c6d53c97fe263ccefb7a7e412d8938e226a
  on:
    branch: main
