dist: xenial
sudo: false

language: node_js

node_js:
  - "0.10.36"
  - "10"
  - "14"

npm:
  - "6.14"

services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin   #login to dockerhub
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  #login to registry.heroku.com

script:
  - docker build -t mvestro/my-continues-library .
  - docker tag mvestro/my-continues-library registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push mvestro/my-continues-library;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: main
